
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: portafolio
    volumes:
      - ./postgres:/var/lib/poostgresql/data

